### ISSUE TITLE
Azure SQL Edge fails to start in GitHub Actions CI pipeline

### ISSUE THREAD

**Issue by macel94** [macel94/cloudnativeblazorpong#32]
### **Problem Description**

The `docker-compose.ci.yml` works correctly in devcontainer environments but fails when Azure SQL Edge container tries to start in the GitHub Actions CI pipeline. The container cannot find the required DACPAC file, causing the database initialization to fail.

### **Root Cause**

1. **Missing Environment Variable**: The `docker-compose.ci.yml` uses `${LOCAL_WORKSPACE_FOLDER}` which is a VS Code devcontainer-specific variable that doesn't exist in GitHub Actions environments.

2. **Missing Database Build Step**: The CI workflow (`.github/workflows/ci.yml`) doesn't build the SQL database project before starting the containers, so the DACPAC file (`Blazorpong.DB.AzureSql.dacpac`) doesn't exist in the expected location.

3. **Failed Volume Mount**: When `${LOCAL_WORKSPACE_FOLDER}` is undefined, the volume mount fails:
   ```yaml
   volumes:
     - ${LOCAL_WORKSPACE_FOLDER}/src/Blazorpong.DB.AzureSql/bin/Debug:/backup:ro
   ```

### **Impact**

- CI pipeline fails during container startup
- Azure SQL Edge container cannot initialize with the database schema
- SignalR service fails to start due to `condition: service_healthy` dependency on Azure SQL
- End-to-end tests cannot run

#### **Step 1: Update docker-compose.ci.yml**

Replace all `${LOCAL_WORKSPACE_FOLDER}` references with `${WORKSPACE_FOLDER:-./relative-path}` pattern:

```yaml
# Azure SQL service
azuresql:
  image: "mcr.microsoft.com/azure-sql-edge:latest"
  container_name: azuresql
  volumes:
    - ${WORKSPACE_FOLDER:-./Blazorpong.DB.AzureSql/bin/Debug}:/backup:ro
  # ... rest of config

# Apply same pattern to other services:
prometheus:
  volumes:
    - ${WORKSPACE_FOLDER:-./Observability}/prometheus.yaml:/etc/prometheus/prometheus.yaml

collector:
  volumes:
    - ${WORKSPACE_FOLDER:-./Observability}/otel-collector-config.yaml:/etc/collector.yaml

tempo:
  volumes:
    - ${WORKSPACE_FOLDER:-./Observability}/tempo.yaml:/etc/tempo.yaml

grafana:
  volumes:
    - ${WORKSPACE_FOLDER:-./Observability}/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    - ${WORKSPACE_FOLDER:-./Observability}/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
    - ${WORKSPACE_FOLDER:-./Observability}/dashboards:/etc/grafana/dashboards

loki:
  volumes:
    - ${WORKSPACE_FOLDER:-./Observability}/loki.yaml:/etc/loki.yaml

playwright:
  volumes:
    - ${WORKSPACE_FOLDER:-./tests-e2e}:/tests
```

#### **Step 2: Update CI Workflow**

Add database build step and set environment variable in `.github/workflows/ci.yml`:

```yaml
jobs:
  test-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build Database Project
        run: dotnet build src/Blazorpong.DB.AzureSql/Blazorpong.DB.AzureSql.sqlproj -c Debug

      - name: Wait 2 minutes so new images are available
        run: sleep 120

      - name: Start services with Docker Compose, test
        run: docker compose -f src/docker-compose.ci.yml up -d
        env:
          WORKSPACE_FOLDER: ${{ github.workspace }}/src
```

### **Why This Solution Works**

- **Backward Compatible**: Doesn't affect existing devcontainer setup (`docker-compose.yml` remains unchanged)
- **Environment Agnostic**: Uses fallback values for local testing
- **Explicit Dependencies**: Ensures DACPAC file exists before container startup
- **Proper Variable Scoping**: Uses GitHub Actions workspace variables in CI context

### **Verification**

After implementing these changes:
1. Database project builds successfully in CI
2. DACPAC file exists at expected location
3. Azure SQL Edge container starts and passes health checks
4. SignalR service can connect to database
5. End-to-end tests can run successfully
